[package]
name = "ray"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bytemuck = { version = "1.22.0", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
pollster = "0.4.0"
wgpu = "24.0.3"
winit = "0.30.9"
